# Generated by Django 5.2.16 on 2026-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('fire_detection', 'Fire Detection System'), ('co2_gas_flooding', 'Co2 Gas Flooding'), ('cctv_pa', 'CCTV & PA System'), ('hvws_mvms', 'HVWS / MVMS System'), ('fire_extinguisher', 'All Type Fire Extinguisher'), ('safety_equipment', 'Safety Equipment'), ('fire_pump_house', 'Fire Pump House'), ('electricals', 'All Type Electricals Work'), ('other', 'Not sure / Other')], default='other', max_length=30)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
