# Generated by Django 5.2.16 on 2026-07-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_consultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyrequest',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
