# Generated by Django 5.2.16 on 2026-09-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_contactmessage_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNotificationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_count', models.PositiveIntegerField(default=0)),
                ('contact_count', models.PositiveIntegerField(default=0)),
                ('consultation_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lead Notification Counter',
                'verbose_name_plural': 'Lead Notification Counter',
            },
        ),
    ]
