# Generated by Django 5.2.16 on 2026-07-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_seed_site_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='clients_served',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
