# Generated by Django 5.2.16 on 2026-07-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_sitesetting_clients_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='emergency_support',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='installations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
