# Generated by Django 5.2.16 on 2026-07-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_sitesetting_installations_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='team_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
