# Generated by Django 5.2.16 on 2026-07-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_sitesetting_team_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
