# Generated by Django 5.2.16 on 2026-08-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_seed_process_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='processphase',
            name='card1_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='processphase',
            name='card1_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='processphase',
            name='card2_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='processphase',
            name='card2_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
