# Generated by Django 5.2.16 on 2026-08-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_seed_process_phase_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='processphase',
            name='tagline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='processphase',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
