# Generated by Django 5.2.16 on 2026-08-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_seed_hero_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_slide_duration_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
