# Generated by Django 5.2.16 on 2026-08-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_sitesetting_hero_slide_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='brochure/')),
            ],
            options={
                'verbose_name': 'Brochure',
                'verbose_name_plural': 'Brochure',
            },
        ),
    ]
