# Generated by Django 5.2.16 on 2026-08-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_seed_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='image',
            field=models.ImageField(default='', upload_to='brochure/'),
        ),
    ]
