# Generated by Django 5.2.16 on 2026-08-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_seed_fire_hydrant_system_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
