# Generated by Django 5.2.16 on 2026-09-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_generalize_blog_post_service_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='lead_notification_threshold',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
