# Generated by Django 5.2.16 on 2026-09-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_seed_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
