from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from core.api_views import (
    AdminHubChangeEmailRequestOTPView,
    AdminHubChangeEmailRevertView,
    AdminHubChangeEmailVerifyOTPView,
    AdminHubChangePasswordView,
    AdminHubChangeUsernameView,
    AdminHubForgotPasswordRequestOTPView,
    AdminHubForgotPasswordResetView,
    AdminHubForgotPasswordVerifyOTPView,
    AdminHubLoginAPIView,
    BrandDetailView,
    BrandListCreateView,
    CertificationDeleteView,
    CertificationListCreateView,
    ClientLogoDetailView,
    ClientLogoListCreateView,
    ConsultationRequestCreateView,
    ContactMessageCreateView,
    FireRiskAssessmentItemDetailView,
    FireRiskAssessmentItemListCreateView,
    MissionVisionItemDetailView,
    MissionVisionItemListView,
    ProductDetailView,
    ProductListCreateView,
    ServiceDetailView,
    ServiceListCreateView,
    SiteSettingDetailView,
    SurveyRequestCreateView,
)
from core.sitemaps import StaticViewSitemap
from core.views import (
    AboutView,
    AdminHubCertificationsView,
    AdminHubClienteleView,
    AdminHubHomeView,
    AdminHubLeadsView,
    AdminHubLoginView,
    AdminHubResolveLeadView,
    AdminHubServicesView,
    BrochureView,
    CertificationsView,
    ClienteleView,
    ConsultationView,
    ContactPageView,
    HomeView,
    ProcessView,
    RobotsTxtView,
    ServicesView,
    SurveyPageView,
)

sitemaps = {'static': StaticViewSitemap()}

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('robots.txt', RobotsTxtView.as_view(), name='robots-txt'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('about/', AboutView.as_view(), name='about'),
    path('clientele/', ClienteleView.as_view(), name='clientele'),
    path('services/', ServicesView.as_view(), name='services'),
    path('process/', ProcessView.as_view(), name='process'),
    path('brochure/', BrochureView.as_view(), name='brochure'),
    path('certifications/', CertificationsView.as_view(), name='certifications'),
    path('survey/', SurveyPageView.as_view(), name='survey'),
    path('api/survey/', SurveyRequestCreateView.as_view(), name='api-survey'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('api/contact/', ContactMessageCreateView.as_view(), name='api-contact'),
    path('consultation/', ConsultationView.as_view(), name='consultation'),
    path('api/consultation/', ConsultationRequestCreateView.as_view(), name='api-consultation'),
    path('admin-hub/', AdminHubLoginView.as_view(), name='adminhub-login'),
    path('api/admin-hub/login/', AdminHubLoginAPIView.as_view(), name='api-adminhub-login'),
    path('api/admin-hub/forgot-password/request-otp/', AdminHubForgotPasswordRequestOTPView.as_view(), name='api-adminhub-forgot-password-request-otp'),
    path('api/admin-hub/forgot-password/verify-otp/', AdminHubForgotPasswordVerifyOTPView.as_view(), name='api-adminhub-forgot-password-verify-otp'),
    path('api/admin-hub/forgot-password/reset/', AdminHubForgotPasswordResetView.as_view(), name='api-adminhub-forgot-password-reset'),
    path('admin-hub/home/', AdminHubHomeView.as_view(), name='adminhub-home'),
    path('admin-hub/leads/', AdminHubLeadsView.as_view(), name='adminhub-leads'),
    path('admin-hub/leads/resolve/<str:lead_type>/<int:pk>/', AdminHubResolveLeadView.as_view(), name='adminhub-leads-resolve'),
    path('admin-hub/clientele/', AdminHubClienteleView.as_view(), name='adminhub-clientele'),
    path('admin-hub/services/', AdminHubServicesView.as_view(), name='adminhub-services'),
    path('admin-hub/certifications/', AdminHubCertificationsView.as_view(), name='adminhub-certifications'),
    path('admin-hub/logout/', LogoutView.as_view(next_page='adminhub-login'), name='adminhub-logout'),
    path('api/admin-hub/change-password/', AdminHubChangePasswordView.as_view(), name='api-adminhub-change-password'),
    path('api/admin-hub/change-username/', AdminHubChangeUsernameView.as_view(), name='api-adminhub-change-username'),
    path('api/admin-hub/change-email/request-otp/', AdminHubChangeEmailRequestOTPView.as_view(), name='api-adminhub-change-email-request-otp'),
    path('api/admin-hub/change-email/verify/', AdminHubChangeEmailVerifyOTPView.as_view(), name='api-adminhub-change-email-verify'),
    path('api/admin-hub/change-email/revert/', AdminHubChangeEmailRevertView.as_view(), name='api-adminhub-change-email-revert'),
    path('api/admin-hub/mission-vision/', MissionVisionItemListView.as_view(), name='api-adminhub-mission-vision-list'),
    path('api/admin-hub/mission-vision/<int:pk>/', MissionVisionItemDetailView.as_view(), name='api-adminhub-mission-vision-detail'),
    path('api/admin-hub/client-logos/', ClientLogoListCreateView.as_view(), name='api-adminhub-client-logos-list'),
    path('api/admin-hub/client-logos/<int:pk>/', ClientLogoDetailView.as_view(), name='api-adminhub-client-logos-detail'),
    path('api/admin-hub/brands/', BrandListCreateView.as_view(), name='api-adminhub-brands-list'),
    path('api/admin-hub/brands/<int:pk>/', BrandDetailView.as_view(), name='api-adminhub-brands-detail'),
    path('api/admin-hub/services/', ServiceListCreateView.as_view(), name='api-adminhub-services-list'),
    path('api/admin-hub/services/<int:pk>/', ServiceDetailView.as_view(), name='api-adminhub-services-detail'),
    path('api/admin-hub/fire-risk-items/', FireRiskAssessmentItemListCreateView.as_view(), name='api-adminhub-fire-risk-items-list'),
    path('api/admin-hub/fire-risk-items/<int:pk>/', FireRiskAssessmentItemDetailView.as_view(), name='api-adminhub-fire-risk-items-detail'),
    path('api/admin-hub/products/', ProductListCreateView.as_view(), name='api-adminhub-products-list'),
    path('api/admin-hub/products/<int:pk>/', ProductDetailView.as_view(), name='api-adminhub-products-detail'),
    path('api/admin-hub/certifications/', CertificationListCreateView.as_view(), name='api-adminhub-certifications-list'),
    path('api/admin-hub/certifications/<int:pk>/', CertificationDeleteView.as_view(), name='api-adminhub-certifications-detail'),
    path('api/admin-hub/site-settings/', SiteSettingDetailView.as_view(), name='api-adminhub-site-settings-detail'),
]
