from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from core.api_views import (
    AdminHubChangeEmailRequestOTPView,
    AdminHubChangeEmailRevertView,
    AdminHubChangeEmailVerifyOTPView,
    AdminHubChangePasswordView,
    AdminHubChangeUsernameView,
    AdminHubForgotPasswordRequestOTPView,
    AdminHubForgotPasswordResetView,
    AdminHubForgotPasswordVerifyOTPView,
    AdminHubLoginAPIView,
    BlogPostDetailView,
    BlogPostListCreateView,
    BrochureDetailView,
    CertificationDeleteView,
    CertificationListCreateView,
    ClientLogoDetailView,
    ClientLogoListCreateView,
    ConsultationRequestCreateView,
    ContactMessageCreateView,
    FireRiskAssessmentItemDetailView,
    FireRiskAssessmentItemListCreateView,
    HeroSlideDeleteView,
    HeroSlideListCreateView,
    MissionVisionItemDetailView,
    MissionVisionItemListView,
    ProcessPhaseDetailView,
    ProcessPhaseListCreateView,
    ProductDetailView,
    ProductListCreateView,
    PublicTestimonialListCreateView,
    ServiceDetailView,
    ServiceListCreateView,
    SiteSettingDetailView,
    SurveyRequestCreateView,
    TestimonialDetailView,
    TestimonialListCreateView,
)
from core.sitemaps import BlogPostSitemap, LocationSitemap, StaticViewSitemap
from core.views import (
    AboutView,
    AdminHubApproveFeedbackView,
    AdminHubBlogView,
    AdminHubCertificationsView,
    AdminHubClienteleView,
    AdminHubFeedbackView,
    AdminHubHomeView,
    AdminHubLeadsView,
    AdminHubLoginView,
    AdminHubProcessView,
    AdminHubResolveLeadView,
    AdminHubServicesView,
    BlogDetailView,
    BlogListView,
    BrochureView,
    CertificationsView,
    ClienteleView,
    ConsultationView,
    ContactPageView,
    FeedbackPageView,
    FireAlarmSystemView,
    FireExtinguishersView,
    FireHydrantSystemView,
    FirePumpHouseView,
    GasDetectionSystemView,
    GasSuppressionSystemView,
    HomeView,
    HvwsMvwsSystemView,
    LocationView,
    PavaSystemView,
    ProcessView,
    RobotsTxtView,
    SafetyEquipmentView,
    ServicesView,
    SurveyPageView,
)

sitemaps = {'static': StaticViewSitemap(), 'blog': BlogPostSitemap(), 'locations': LocationSitemap()}

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('robots.txt', RobotsTxtView.as_view(), name='robots-txt'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('about/', AboutView.as_view(), name='about'),
    path('clientele/', ClienteleView.as_view(), name='clientele'),
    path('services/', ServicesView.as_view(), name='services'),
    path('services/fire-alarm-system/', FireAlarmSystemView.as_view(), name='service-fire-alarm-system'),
    path('services/gas-detection-system/', GasDetectionSystemView.as_view(), name='service-gas-detection-system'),
    path('services/gas-suppression-system/', GasSuppressionSystemView.as_view(), name='service-gas-suppression-system'),
    path('services/hvws-mvws-system/', HvwsMvwsSystemView.as_view(), name='service-hvws-mvws-system'),
    path('services/fire-extinguishers/', FireExtinguishersView.as_view(), name='service-fire-extinguishers'),
    path('services/safety-equipment/', SafetyEquipmentView.as_view(), name='service-safety-equipment'),
    path('services/fire-pump-house/', FirePumpHouseView.as_view(), name='service-fire-pump-house'),
    path('services/fire-hydrant-system/', FireHydrantSystemView.as_view(), name='service-fire-hydrant-system'),
    path('services/pava-system/', PavaSystemView.as_view(), name='service-pava-system'),
    path('process/', ProcessView.as_view(), name='process'),
    path('brochure/', BrochureView.as_view(), name='brochure'),
    path('certifications/', CertificationsView.as_view(), name='certifications'),
    path('blog/', BlogListView.as_view(), name='blog'),
    path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blog-detail'),
    path('locations/<slug:slug>/', LocationView.as_view(), name='location'),
    path('survey/', SurveyPageView.as_view(), name='survey'),
    path('api/survey/', SurveyRequestCreateView.as_view(), name='api-survey'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('api/contact/', ContactMessageCreateView.as_view(), name='api-contact'),
    path('consultation/', ConsultationView.as_view(), name='consultation'),
    path('api/consultation/', ConsultationRequestCreateView.as_view(), name='api-consultation'),
    path('api/testimonials/', PublicTestimonialListCreateView.as_view(), name='api-testimonials-public'),
    path('feedback/', FeedbackPageView.as_view(), name='feedback'),
    path('admin-hub/', AdminHubLoginView.as_view(), name='adminhub-login'),
    path('api/admin-hub/login/', AdminHubLoginAPIView.as_view(), name='api-adminhub-login'),
    path('api/admin-hub/forgot-password/request-otp/', AdminHubForgotPasswordRequestOTPView.as_view(), name='api-adminhub-forgot-password-request-otp'),
    path('api/admin-hub/forgot-password/verify-otp/', AdminHubForgotPasswordVerifyOTPView.as_view(), name='api-adminhub-forgot-password-verify-otp'),
    path('api/admin-hub/forgot-password/reset/', AdminHubForgotPasswordResetView.as_view(), name='api-adminhub-forgot-password-reset'),
    path('admin-hub/home/', AdminHubHomeView.as_view(), name='adminhub-home'),
    path('admin-hub/leads/', AdminHubLeadsView.as_view(), name='adminhub-leads'),
    path('admin-hub/leads/resolve/<str:lead_type>/<int:pk>/', AdminHubResolveLeadView.as_view(), name='adminhub-leads-resolve'),
    path('admin-hub/feedback/', AdminHubFeedbackView.as_view(), name='adminhub-feedback'),
    path('admin-hub/feedback/approve/<int:pk>/', AdminHubApproveFeedbackView.as_view(), name='adminhub-feedback-approve'),
    path('admin-hub/clientele/', AdminHubClienteleView.as_view(), name='adminhub-clientele'),
    path('admin-hub/services/', AdminHubServicesView.as_view(), name='adminhub-services'),
    path('admin-hub/process/', AdminHubProcessView.as_view(), name='adminhub-process'),
    path('admin-hub/certifications/', AdminHubCertificationsView.as_view(), name='adminhub-certifications'),
    path('admin-hub/blog/', AdminHubBlogView.as_view(), name='adminhub-blog'),
    path('admin-hub/logout/', LogoutView.as_view(next_page='adminhub-login'), name='adminhub-logout'),
    path('api/admin-hub/change-password/', AdminHubChangePasswordView.as_view(), name='api-adminhub-change-password'),
    path('api/admin-hub/change-username/', AdminHubChangeUsernameView.as_view(), name='api-adminhub-change-username'),
    path('api/admin-hub/change-email/request-otp/', AdminHubChangeEmailRequestOTPView.as_view(), name='api-adminhub-change-email-request-otp'),
    path('api/admin-hub/change-email/verify/', AdminHubChangeEmailVerifyOTPView.as_view(), name='api-adminhub-change-email-verify'),
    path('api/admin-hub/change-email/revert/', AdminHubChangeEmailRevertView.as_view(), name='api-adminhub-change-email-revert'),
    path('api/admin-hub/mission-vision/', MissionVisionItemListView.as_view(), name='api-adminhub-mission-vision-list'),
    path('api/admin-hub/mission-vision/<int:pk>/', MissionVisionItemDetailView.as_view(), name='api-adminhub-mission-vision-detail'),
    path('api/admin-hub/client-logos/', ClientLogoListCreateView.as_view(), name='api-adminhub-client-logos-list'),
    path('api/admin-hub/client-logos/<int:pk>/', ClientLogoDetailView.as_view(), name='api-adminhub-client-logos-detail'),
    path('api/admin-hub/services/', ServiceListCreateView.as_view(), name='api-adminhub-services-list'),
    path('api/admin-hub/services/<int:pk>/', ServiceDetailView.as_view(), name='api-adminhub-services-detail'),
    path('api/admin-hub/fire-risk-items/', FireRiskAssessmentItemListCreateView.as_view(), name='api-adminhub-fire-risk-items-list'),
    path('api/admin-hub/fire-risk-items/<int:pk>/', FireRiskAssessmentItemDetailView.as_view(), name='api-adminhub-fire-risk-items-detail'),
    path('api/admin-hub/testimonials/', TestimonialListCreateView.as_view(), name='api-adminhub-testimonials-list'),
    path('api/admin-hub/testimonials/<int:pk>/', TestimonialDetailView.as_view(), name='api-adminhub-testimonials-detail'),
    path('api/admin-hub/products/', ProductListCreateView.as_view(), name='api-adminhub-products-list'),
    path('api/admin-hub/products/<int:pk>/', ProductDetailView.as_view(), name='api-adminhub-products-detail'),
    path('api/admin-hub/process-phases/', ProcessPhaseListCreateView.as_view(), name='api-adminhub-process-phases-list'),
    path('api/admin-hub/process-phases/<int:pk>/', ProcessPhaseDetailView.as_view(), name='api-adminhub-process-phases-detail'),
    path('api/admin-hub/hero-slides/', HeroSlideListCreateView.as_view(), name='api-adminhub-hero-slides-list'),
    path('api/admin-hub/hero-slides/<int:pk>/', HeroSlideDeleteView.as_view(), name='api-adminhub-hero-slides-detail'),
    path('api/admin-hub/certifications/', CertificationListCreateView.as_view(), name='api-adminhub-certifications-list'),
    path('api/admin-hub/certifications/<int:pk>/', CertificationDeleteView.as_view(), name='api-adminhub-certifications-detail'),
    path('api/admin-hub/blog/', BlogPostListCreateView.as_view(), name='api-adminhub-blog-list'),
    path('api/admin-hub/blog/<int:pk>/', BlogPostDetailView.as_view(), name='api-adminhub-blog-detail'),
    path('api/admin-hub/site-settings/', SiteSettingDetailView.as_view(), name='api-adminhub-site-settings-detail'),
    path('api/admin-hub/brochure/', BrochureDetailView.as_view(), name='api-adminhub-brochure-detail'),
]
