from django.core.exceptions import ImproperlyConfigured

from .base import *  # noqa: F401,F403

DEBUG = False

# base.py falls back to a known, publicly-visible insecure SECRET_KEY when
# SECRET_KEY isn't set in .env, so local dev never hard-fails on a missing
# env file. That fallback must never reach production — fail closed instead
# of silently booting with a key an attacker could look up in this repo.
if not SECRET_KEY or SECRET_KEY == 'django-insecure-change-me-in-.env':
    raise ImproperlyConfigured(
        'SECRET_KEY is missing or still set to the insecure development '
        'default. Set a real, unique SECRET_KEY in the production .env '
        'before starting this server.'
    )

# Deliberately NOT fail-closed (unlike SECRET_KEY above): the key is
# generated by hand at the client's office and may not exist yet at first
# deploy. Boot without it — only the Admin Hub's "Forgot Password" and
# "Change Email" OTP flows depend on SendGrid, and they'll surface a clean
# error at send time instead of blocking the whole site.
if not ANYMAIL.get('SENDGRID_API_KEY'):
    import warnings
    warnings.warn(
        'SENDGRID_API_KEY is not set — Admin Hub "Forgot Password" and '
        '"Change Email" OTP emails will fail until it is added.',
        RuntimeWarning,
    )

# No TLS yet — this VM is reachable over plain HTTP via its IP until a
# domain is bought and certbot is wired into nginx (see CLAUDE.md's Oracle
# migration section). Redirecting to https before that exists would make
# the site completely unreachable, so this defaults to False here (unlike
# prod.py's default of True) until that later phase flips it via env.
_TLS_ENABLED = env.bool('SECURE_SSL_REDIRECT', default=False)
SECURE_SSL_REDIRECT = _TLS_ENABLED
SESSION_COOKIE_SECURE = _TLS_ENABLED
CSRF_COOKIE_SECURE = _TLS_ENABLED

# Standard hardening for once this sits behind nginx terminating TLS.
# Harmless (unused) while there's no HTTPS yet.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Must list the VM's reserved public IP (as http://<ip>) and, once bought,
# the custom domain — otherwise POSTs (including the React islands' fetch
# calls) 403 on CSRF even though ALLOWED_HOSTS accepts the request.
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

DJANGO_VITE = {
    'default': {
        'dev_mode': False,
        'manifest_path': BASE_DIR / 'frontend' / 'dist' / '.vite' / 'manifest.json',
    }
}

# Deliberately no WhiteNoise and no Cloudinary here, unlike prod.py:
#
# - Static/media are served directly by nginx (see deploy/oracle/nginx.conf)
#   sitting in front of gunicorn — the "separate static-file proxy" Render's
#   native web services don't have, which is the whole reason prod.py needs
#   WhiteNoise in the first place.
# - Media uses base.py's plain FileSystemStorage default (MEDIA_ROOT) since
#   this VM's disk persists across restarts/deploys, unlike Render's
#   ephemeral web-service disk. No Cloudinary account needed here.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Anymail's SendGrid backend (base.py) issues anymail.W003 on every boot —
# accepted knowingly, see base.py's comment beside SILENCED_SYSTEM_CHECKS.
# Re-declared here since Django's --deploy check only reads the final
# resolved settings module.
SILENCED_SYSTEM_CHECKS = ['anymail.W003']


# Without an explicit LOGGING config, Django's built-in default only sends
# request errors to console when DEBUG=True — under DEBUG=False with no
# ADMINS/email handler configured, a 500 error produces zero log output.
# systemd/journalctl captures whatever gunicorn writes to stdout/stderr, so
# route errors there explicitly (same reasoning as prod.py's Render setup).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
