from django.core.exceptions import ImproperlyConfigured

from .base import *  # noqa: F401,F403

DEBUG = False

# base.py falls back to a known, publicly-visible insecure SECRET_KEY when
# SECRET_KEY isn't set in .env, so local dev never hard-fails on a missing
# env file. That fallback must never reach production — fail closed instead
# of silently booting with a key an attacker could look up in this repo.
if not SECRET_KEY or SECRET_KEY == 'django-insecure-change-me-in-.env':
    raise ImproperlyConfigured(
        'SECRET_KEY is missing or still set to the insecure development '
        'default. Set a real, unique SECRET_KEY in the production .env '
        'before starting this server.'
    )

# Deliberately NOT fail-closed (unlike SECRET_KEY/CLOUDINARY_* below): the
# key is being generated by hand at the client's office and may not exist
# yet at first deploy. Boot without it — only the Admin Hub's "Forgot
# Password" and "Change Email" OTP flows depend on SendGrid, and they'll
# surface a clean error at send time instead of blocking the whole site.
if not ANYMAIL.get('SENDGRID_API_KEY'):
    import warnings
    warnings.warn(
        'SENDGRID_API_KEY is not set — Admin Hub "Forgot Password" and '
        '"Change Email" OTP emails will fail until it is added.',
        RuntimeWarning,
    )

SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Standard hardening for a deployment behind a TLS-terminating reverse proxy.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Render terminates TLS at a proxy in front of the app and assigns an
# onrender.com subdomain; a custom domain, if added later, must be listed
# here too or its POSTs (including the React islands' fetch calls) will
# 403 on CSRF even though ALLOWED_HOSTS accepts the request.
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

DJANGO_VITE = {
    'default': {
        'dev_mode': False,
        'manifest_path': BASE_DIR / 'frontend' / 'dist' / '.vite' / 'manifest.json',
    }
}


# WhiteNoise serves collected static files directly from the app process —
# Render's native (non-Docker) web services have no separate static-file
# proxy/CDN in front of them, so without this, /static/ 404s in production
# even though `collectstatic` ran. Inserted right after SecurityMiddleware
# per WhiteNoise's own install docs (must run before anything that might
# short-circuit the response).
MIDDLEWARE = MIDDLEWARE.copy()
MIDDLEWARE.insert(
    MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
    'whitenoise.middleware.WhiteNoiseMiddleware',
)

# Cloudinary holds user-uploaded media (client logos, brand/service/product
# images, certification images+PDFs, brochure, blog images) — Render's web
# service disk is ephemeral and wipes on every deploy/restart, so local
# FileSystemStorage (base.py's default, fine for dev) can't be used here.
INSTALLED_APPS = INSTALLED_APPS + ['cloudinary_storage', 'cloudinary']

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': env('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default=''),
}
if not all(CLOUDINARY_STORAGE.values()):
    raise ImproperlyConfigured(
        'CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET '
        'are missing. Set all three in the production .env before starting '
        'this server — uploaded media has nowhere durable to live without '
        'them (Render\'s web service disk does not persist across deploys).'
    )

STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Anymail's SendGrid backend (base.py) issues anymail.W003 on every boot —
# accepted knowingly, see base.py's comment beside SILENCED_SYSTEM_CHECKS.
# Re-declared here since Django's --deploy check only reads the final
# resolved settings module.
SILENCED_SYSTEM_CHECKS = ['anymail.W003']


# Without an explicit LOGGING config, Django's built-in default only sends
# request errors to console when DEBUG=True — under DEBUG=False with no
# ADMINS/email handler configured, a 500 error produces zero log output.
# Render captures whatever the process writes to stdout, so route errors
# there explicitly.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
